logging:
  config: classpath:logback-dev.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admin?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 500
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-wait: -1
        max-idle: 8